# Generated by Django 5.0.1 on 2024-04-23 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
