# Generated by Django 5.0.1 on 2024-04-25 17:05

import post.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_content_alter_post_created_at_alter_post_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to='post/file/', validators=[post.validators.validate_file_extension]),
        ),
    ]
