# Generated by Django 5.0.1 on 2024-04-25 17:42

import post.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to='posts/files/%Y/%m/%d', validators=[post.validators.validate_file_extension]),
        ),
    ]
