# Generated by Django 5.1 on 2024-11-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0008_alter_post_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-is_pinned", "-created_at"]},
        ),
        migrations.AddField(
            model_name="post",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
