# Generated by Django 5.1 on 2024-12-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0009_alter_post_options_post_is_pinned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=40, verbose_name="제목"),
        ),
    ]
